### ISSUE TITLE
Code generation bug

### ISSUE THREAD

**Issue by gucki** [yury/coffee-views#2]
The following code produces strange javascript:

Coffeescript:

```
test =
  "<%='key'%>": <%='value'%>
```

Generated code:

```
test = {
      "`"key"`": "value"
    };
```

Expected code:

```
test = {
      "key": "value"
    };
```

Also using "raw"  output does not work, it produces:

```
test = {
      "`key`": "value"
    };
```

**Comment by gucki** [comment]
Here's an even simpler example:

```
test(<%=5%>)
=> test(5);

test("<%=5%>")
=> test("`5`");

test("<%==5%>")
=> test("`5`");
```

    test(<%=5.to_s%>)
    => test("5");

I really wonder where these annoying backticks come from....

**Comment by yury** [comment]
It because of "".
In coffee script strings use #{= } syntax.

``` coffeescript
test =
  "#{='key'}": <%='value'%>
```
